# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'RSExample' do
	pod 'RealmSwift' 
end

target 'RSExampleTests' do
	pod 'RealmSwift' 
end

